#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-$(CONFIG_DRM_XLNX) += xlnx_drm.o
obj-$(CONFIG_DRM_XLNX_DP) += xlnx_dp.o
obj-$(CONFIG_DRM_ZYNQMP_DP_SUB) += zynqmp_dp_sub.o
